### ISSUE TITLE
argon2

### ISSUE THREAD

**Issue by Sev767** [ranisalt/node-argon2#118] opened 2018-02-27 19:32 UTC
I am having the same issue 
npm v 5.6.0
node v8.9.4
using npm install argon2

```
1171 verbose stack Error: argon2@0.17.2 install: `node-gyp rebuild`
1171 verbose stack Exit status 1
1171 verbose stack     at EventEmitter.<anonymous> (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
1171 verbose stack     at emitTwo (events.js:126:13)
1171 verbose stack     at EventEmitter.emit (events.js:214:7)
1171 verbose stack     at ChildProcess.<anonymous> (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1171 verbose stack     at emitTwo (events.js:126:13)
1171 verbose stack     at ChildProcess.emit (events.js:214:7)
1171 verbose stack     at maybeClose (internal/child_process.js:925:16)
1171 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1172 verbose pkgid argon2@0.17.2
1173 verbose cwd C:\git\FP-Projects\NportWeb
1174 verbose Windows_NT 10.0.15063
1175 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "argon2"
1176 verbose node v8.9.4
1177 verbose npm  v5.6.0
1178 error code ELIFECYCLE
1179 error errno 1
1180 error argon2@0.17.2 install: `node-gyp rebuild`
1180 error Exit status 1
1181 error Failed at the argon2@0.17.2 install script.
1181 error This is probably not a problem with npm. There is likely additional logging output above.
1182 verbose exit [ 1, true ]
```

**Comment by ranisalt** [comment] 2018-02-28 02:33
Might be duplicate of #109

**Closed** 2018-03-27 02:19 UTC
Labels: duplicate
