### ISSUE TITLE
Builds are non-deterministic

### ISSUE THREAD

**Issue by unusualbob** [ranisalt/node-argon2#206] opened 2019-09-10 18:27 UTC
## Steps to reproduce
1. Run node-gyp rebuild argon2
2. Rename build folder build2
3. Run node-gyp rebuild argon2
4. diff build/Release/argon2.a build2/Release/argon2.a
5. Files **do not match**

### Expected behaviour
Two builds of the same binary on the same machine should be identical

### Actual behaviour
The builds are slightly off, likely due to a timestamp being used somewhere

### Environment
Attempted this on two different environments (to see if OS or compiler was the cause)
Ubuntu 18.x / Centos

**Compiler version:**
gcc 7.4.0 Ubuntu / 7.3.1 Centos

### Other notes
I have tried setting SOURCE_DATE_EPOCH and ZERO_AR_DATE in the terminal when building to no effect.

**Comment by ranisalt** [comment] 2019-09-10 20:19
I can't reproduce. I consistently get the same sha256 hash from rebuilds.

**Comment by unusualbob** [comment] 2019-09-10 22:39
Well I built a dockerfile to disprove that and then the builds were identical. Going to see if I can now determine the cause of our build discrepancy. Thanks for your time, will close for now.

**Comment by ranisalt** [comment] 2019-09-10 23:27
No problem, if you find this issue again please reopen.

**Comment by unusualbob** [comment] 2019-09-11 23:04
Ok so I actually was able to reproduce, but possibly only on centos. Here's a docker image that will do it:

```Docker
FROM amazonlinux

RUN yum -y groupinstall "Development Tools"
RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash - && yum -y install nodejs && yum clean all && rm -rf /var/cache/yum

RUN mkdir dir1 && cd dir1 && npm install argon2@0.19.3
RUN mkdir dir2 && cd dir2 && npm install argon2@0.19.3

RUN diff dir1/node_modules/argon2/build/Release/argon2.a dir2/node_modules/argon2/build/Release/argon2.a
```
If you build this image it will fail on the last step as diff will fail. The gcc version that is being used here is `gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)`

**Comment by unusualbob** [comment] 2019-09-11 23:34
I'll also add that they match perfectly when built in debian:

```
FROM node:8-stretch

RUN mkdir dir1 && cd dir1 && npm install argon2@0.19.3
RUN mkdir dir2 && cd dir2 && npm install argon2@0.19.3

RUN gcc --version
RUN diff dir1/node_modules/argon2/build/Release/argon2.a  dir2/node_modules/argon2/build/Release/argon2.a
```
That container uses `gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516` so maybe it's something in gcc 7?

**Comment by ranisalt** [comment] 2019-09-12 02:16
I can't provide support for old versions of the lib.

**Comment by ranisalt** [comment] 2022-08-22 23:26
I checked with v0.29.0, and it seems that two builds produce the same binary. I modified your Dockerfile slightly, to use the latest Node version available (18.x was not installable, 16.x is the latest LTS) and used `--build-from-source` to skip the prebuilt binaries, and compared with `sha256sum` because I though `diff`  would output `binary files X and Y differ/are the same` but it's just silent :sweat_smile: 

So that's what I used:

```
FROM amazonlinux AS base
RUN yum -y groupinstall "Development Tools"
RUN curl --silent --location https://rpm.nodesource.com/setup_16.x | bash - && yum -y install nodejs python3 && yum clean all && rm -rf /var/cache/yum

FROM base AS build1
RUN mkdir dir && cd dir && echo 1 && npm install argon2@0.29.0 --build-from-source

FROM base AS build2
RUN mkdir dir && cd dir && echo 2 && npm install argon2@0.29.0 --build-from-source

FROM amazonlinux AS final
COPY --from=build1 dir/node_modules/argon2/lib/binding/napi-v3/argon2.node argon2a.node
COPY --from=build2 dir/node_modules/argon2/lib/binding/napi-v3/argon2.node argon2b.node
RUN sha256sum argon2a.node argon2b.node
```

And it prints

```
cf7b32b8b16a5e9ed736d13b2f679e4ff8741637cd96879a50521b49165aa224  argon2a.node
cf7b32b8b16a5e9ed736d13b2f679e4ff8741637cd96879a50521b49165aa224  argon2b.node
```

The same happens after running `yarn node-pre-gyp rebuild` on my machine, it will always generate a binary with hash `f0bacd9a81f7730db4b62f73542e1557f8e8e012a8d6d31bb45684531f3ea03f`.

For now, I'm closing the issue as resolved.

**Closed by ranisalt** 2022-08-22 23:26 UTC
