### ISSUE TITLE
Failed to install [windows 10]

### ISSUE THREAD

**Issue by hinell** [ranisalt/node-argon2#109] opened 2018-01-20 13:41 UTC
At first npm installing just hanged on. I restarted it again and then it just failed with the error below.

### Before creating an issue, please be sure to:
- [ ] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior (installed for the first time)
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1) run `npm i -S argon2`
2) .... if hangs on => kill the process, run second command again 
3) get the error

### Expected behaviour
It is expected to install properly.

### Actual behaviour
Throwing error:
```
error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was not found.
Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```
Long:
<details><pre>
Project "E:\pr\realty\node_modules\argon2\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "E:\pr\realty\node_modules\argon2\build\binding.sln" (1) is building "E:\pr\realty\node_modules\argon2\build\argon2.vcxproj.metap roj" (2) on node 1 (default targets).
Project "E:\pr\realty\node_modules\argon2\build\argon2.vcxproj.metaproj" (2) is building "E:\pr\realty\node_modules\argon2\build\libargon 2.vcxproj" (3) on node 1 (default targets).
E:\pr\realty\node_modules\argon2\build\libargon2.vcxproj(20,3): error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" was
not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "E:\pr\realty\node_modules\argon2\build\libargon2.vcxproj" (default targets) -- FAILED.

Done Building Project "E:\pr\realty\node_modules\argon2\build\argon2.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "E:\pr\realty\node_modules\argon2\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"E:\pr\realty\node_modules\argon2\build\binding.sln" (default target) (1) ->
"E:\pr\realty\node_modules\argon2\build\argon2.vcxproj.metaproj" (default target) (2) ->
"E:\pr\realty\node_modules\argon2\build\libargon2.vcxproj" (default target) (3) ->
  E:\pr\realty\node_modules\argon2\build\libargon2.vcxproj(20,3): error MSB4019: The imported project "E:\Microsoft.Cpp.Default.props" wa s not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

0 Warning(s)
1 Error(s)

Time Elapsed 00:00:00.92
</pre></details>

### Environment
**Operating system**: `Windows 10 Pro`
**Node version:** `v9.4.0`
**Compiler version:** `Microsoft (R) Build Engine version 14.0.23107.0`

**Comment by ranisalt** [comment] 2018-01-20 20:08
Are you using VS or what? I'll try to reproduce on a VM.

**Comment by hinell** [comment] 2018-01-20 22:23
>VS 

@ranisalt Are you meaning visual studio? If yes then I don't.

**Comment by ranisalt** [comment] 2018-01-21 03:33
Ok then 👍 . I asked because I don't know how Node works on Windows.

**Comment by ranisalt** [comment] 2018-01-21 21:12
Ok, I could do it:

First, install `windows-build-tools` globally with `npm --add-python-to-path i -g windows-build-tools`. It takes a very long time. Then, install `argon2` as you would, and it should compile without issues.

**Comment by hinell** [comment] 2018-01-22 19:05
@ranisalt But what if I have `python` in my `PATH`?

**Comment by hinell** [comment] 2018-01-22 19:36
@ranisalt But what if I already have `python 2.7.14` already in my `PATH`?
Is there anyway to avoid its installation?

**Comment by hinell** [comment] 2018-01-22 20:23
@ranisalt Well, I followed these steps but just got this:
```
fatal error LNK1107: invalid or corrupt file: cannot read at 0x28652D
[E:\pr\xxxxxx\node_modules\argon2\build\argon2.vcxproj]
```

Any ideas?

**Comment by ranisalt** [comment] 2018-01-23 01:52
> @ranisalt But what if I already have python 2.7.14 in my PATH?

It does not mess with your path if you omit the flag.

> fatal error LNK1107: invalid or corrupt file: cannot read at 0x28652D

Try to clean (`npm run clean` should do the trick) and compile again.

**Comment by hinell** [comment] 2018-01-23 09:09
@ranisalt I used it already but the issue still the same. 
Logs show nothing useful.

**Comment by hinell** [comment] 2018-01-25 12:57
@ranisalt Ping

**Comment by ranisalt** [comment] 2018-01-27 01:23
That's a VS issue. You might try to find help at MSDN/Visual Studio forums or wait until someone more knowledgeable of Windows can help.

I couldn't reproduce and figure out what happens :( but a file passed to the compiler is broken, probably a linked lib since you cleaned node-argon2 files.

**Comment by hinell** [comment] 2018-01-29 07:59
@ranisalt What does that `argon2.vcxproj` file do?

**Comment by ATakaSKY** [comment] 2018-02-21 04:32
Same error. Any solution yet?

**Comment by hinell** [comment] 2018-03-04 20:37
@ATakaSKY Still persists.

**Comment by ATakaSKY** [comment] 2018-03-09 09:55
@hinell Can you direct me to use some good hashing algo till this gets resolved.

**Comment by ATakaSKY** [comment] 2018-03-09 15:45
I ran `npm install --global --production windows-build-tools` and install argon then. It worked fine for me.

**Comment by ranisalt** [comment] 2018-06-01 04:51
Closing due to lack of feedbak. Lots of compilation fixes were issued, if they still persist with v0.19.3 please reopen with new traces.

**Closed by ranisalt** 2018-06-01 04:51 UTC
Labels: help wanted, windows

**Comment by hinell** [comment] 2018-06-03 16:32
@ranisalt Just have installed it recently. I'm gonna checkout it a bit later.
I'll report if something going wrong. Thanks.
