### ISSUE TITLE
Strange issue when using alongside with koa

### ISSUE THREAD

**Issue by jim-y** [ranisalt/node-argon2#33] opened 2016-03-03 12:03 UTC
Hi,

Sorry for linking but I really don't want to copy-paste it here too, so please follow my link to the koa issue I've just created https://github.com/koajs/koa/issues/670 - *koa works strange with node-argon2*. I don't know why it happens but there is a strange timeout in the hash function if I use argon with koa. Examples in the linked issue. I've set up some easy examples to show the "bug".

### Environment
**Operating system**: Mac OS X Yosemite 10.10.5

**Node version:** v5.2.0

**Argon version:** 0.9 (latest)

Cheers

**Comment by PlasmaPower** [comment] 2016-03-03 14:36
I've done some research over at the koa issue (koajs/koa#670) and it appears that argon2 breaks when called from an http server listener. Here's a broken example without koa: https://gist.github.com/PlasmaPower/f3cc2c06875eee760d81

I propose renaming this issue to reflect that it's a problem when used with the http library in general, not just koa.

**Comment by ranisalt** [comment] 2016-03-03 17:34
Please follow #25 which is the same problem. I've been discussing with Nan maintainers too on how to solve this issue, which does not only affects node-argon2 but any package that implements promises on the C++ side.

**Comment by PlasmaPower** [comment] 2016-03-04 00:57
To clarify, this issue is for http servers in general.

**Comment by eden** [comment] 2016-04-05 04:24
I've run into this issue as well and worked around it by using the synchronous methods instead. Unfortunately, it outputs a warning to the console which pollutes my server logs. Can we get rid of the warning until this is resolved or at least only warn once instead of each time? Happy to submit a pull request if you need...

**Comment by ranisalt** [comment] 2016-04-05 20:58
It's because the synchronous methods will be removed before v1.0. I'm working to fix this promise issue soon.

**Comment by ranisalt** [comment] 2016-04-05 22:39
Marking as duplicate of #25 since they are closely related.

**Comment by cjlarose** [comment] 2016-04-07 04:32
One way to fix this issue is to avoid using promises in a C++ module altogether. You can use `node-ffi` to dynamically load the `argon2` library and access it from JavaScript. You can then handle Promises from the JS side and just kind of side-step the problem.

This is the approach I've taken in [argon2-ffi][argon2-ffi]. I don't actually handle promises in my library--it's all callback-based. However, for projects seeking to use `argon2` in a way that isn't synchronous (blocking), it's a suitable alternative for now.

[argon2-ffi]: https://github.com/cjlarose/argon2-ffi

**Closed** 2016-04-07 12:11 UTC
Labels: bug, duplicate, help wanted

**Comment by ranisalt** [comment] 2016-04-07 12:13
@cjlarose no point in using the same code you already maintain.

I'd also suggest that you maintain promise-based options since that's the direction ES2015 is moving towards and more people are using async/await now :smile:
