### ISSUE TITLE
while http server is running argon cannot perform verify and after the request timesout catch blog of promise says decoding failed

### ISSUE THREAD

**Issue by NikosEfthias** [ranisalt/node-argon2#37] opened 2016-03-12 05:25 UTC
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [ x] Checkout to the latest version, **including submodules**
- [ ] Try to find an *isolated* way to reproduce the behavior
- [x ] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1.create a http server
2.on data get the post value
3.on end connect to database(mongodb) and after results come back verify the password sent with http post against hash in db

### Expected behaviour
should end the response with fail or success whether pass is right or wrong
### Actual behaviour
then block or catch block never runs while http socket is opened and when user times out or cancels the request it gives the message "decoding failed" 

### Environment
**Operating system**:
ubuntu 15.10 kernel 4.3
**Node version:**
4x
**Compiler version:**
gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)

**Comment by ranisalt** [comment] 2016-03-12 07:39
Duplicate of #33, seems to be more an issue with v8's promises and I'm trying to workaround.

**Closed** 2016-04-07 12:14 UTC
Labels: bug, duplicate, help wanted
