### ISSUE TITLE
[0.28.1] Node16 on Alpine suffers SIGSEGV error when using argon2 verify

### ISSUE THREAD

**Issue by Tallyrald** [ranisalt/node-argon2#302] opened 2021-06-07 15:30 UTC
### Steps to reproduce
1. Call the argon2.verify function on Node v16.X.X on alpine linux using argon2 v0.28.1

[Click here for reproduction repository](https://github.com/Tallyrald/argon2-sigsegv-repro)

### Expected behaviour
Verify function returns either true or false.

### Actual behaviour
Node exits with SIGSEGV signal.

### Environment
**Operating system**: Alpine linux (official node docker container)

**Node version:** 16.X.X

I'm using Typescript v4.3.2

Issue is specific to Node16 & argon2 v0.28.1. Node14 works fine as well as argon2 v0.27.2 (even on Node16).
I'm not sure whether the verify function is the actual or only culprit, but I've seen in my own application that Node definitely crashes while using this function.

**Comment by LoicMatters** [comment] 2022-01-26 17:02
Hello, any update on this ? Got the same problem today on node 16 running on alpine linux with the 0.28.3 package version.

**Comment by Janl1** [comment] 2022-02-09 22:43
Can confirm the issue. Downgrading to v0.27.2 solves it temporarily.

**Comment by ranisalt** [comment] 2022-02-10 17:24
I can reproduce it, but I could not isolate the root cause yet

**Comment by cateiru** [comment] 2022-07-20 04:23
This seems to be a problem that occurs when the version of Node.js is different between build and runtime.

Alpine Linux is built with Node 14, so the error occurs with Node 16.
https://github.com/ranisalt/node-argon2/blob/master/.github/workflows/release.yml#L71

The solution is to run the build in source with the `npm_config_build_from_source` flag set to true.

```dockerfile
ARG NODE_VERSION=16.2.0

###
# 1. Dependencies
###

# Build with alpine linux
FROM node:${NODE_VERSION}-alpine as dependencies

WORKDIR /home/node/

ENV NODE_ENV development

# Add build from source flag
ENV npm_config_build_from_source true

# Install the tools needed for the build
RUN apk add make g++ python3 git
RUN npm i -g node-pre-gyp

COPY tsconfig.json package.json *package-lock.json ./
RUN npm ci

COPY ts ./ts
# "prod-build" on production
RUN npm run setup && \
    npm prune --production

###
# 2. Application
###

FROM node:${NODE_VERSION}-alpine
WORKDIR /home/node/

COPY --from=dependencies /home/node/node_modules node_modules
COPY --from=dependencies /home/node/built built

COPY package.json ./

ENV PATH="$PATH:/home/node/node_modules/.bin"

RUN chown -R node:node /home/node
USER node

ENV NODE_ENV production

# "start" on production
CMD ["npm", "run", "start"]
```

**Comment by ranisalt** [comment] 2022-07-20 16:03
> This seems to be a problem that occurs when the version of Node.js is different between build and runtime.

Interestingly, this seems to be only happening with Alpine. I can understand why it happens, but I was expecting `node-addon-api`  to get around those differences in versions. In this case, it may be related to musl in a corner case that NAA didn't expect.

**Comment by testtestingtester** [comment] 2022-12-10 15:59
Getting same error...tried everything I could think of...alpine image fails...node image fails...version 0.27.2 fails...anyone knows why it fails?

```
Error: /home/node/api/node_modules/argon2/lib/binding/napi-v3/argon2.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/node/api/node_modules/argon2/argon2.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/node/api/src/app.module.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
```

```
ARG NODE_VERSION=16

###########
# INSTALL #
###########

FROM node:${NODE_VERSION} As install

# 👉 Security: do not use the `root` user.
ENV USER=node

# You can not use `${USER}` here, but reference `/home/node`.
ENV PATH="/home/node/.npm-global/bin:${PATH}"
# 👉 The `--global` install dir
ENV NPM_CONFIG_PREFIX="/home/node/.npm-global"

# All subsequent commands are run as the `node` user.
USER "${USER}"

# Pre-create the target dir for global install.
RUN mkdir -p "${NPM_CONFIG_PREFIX}/lib"

WORKDIR /home/node/api

COPY ./tsconfig*.json ./package*.json ./

# RUN chown -R node:node /home/node

# Install python/pip
# ENV PYTHONUNBUFFERED=1
# RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
# RUN python3 -m ensurepip
# RUN pip3 install --no-cache --upgrade pip setuptools

# 👉 Configure NPM, so pkg get installed with correct credentials.
# Avoids `chmod u+x $DIR` and other workarounds.
RUN npm --global --quiet --no-progress install \
    && npm cache clean --force

#########
# BUILD #
#########

FROM node:${NODE_VERSION} As build

WORKDIR /home/node/api

COPY ./tsconfig*.json ./package*.json ./

COPY --from=install /home/node/api/node_modules ./node_modules

COPY . .

ENV NODE_ENV=production

RUN npm ci --only=production && npm cache clean --force

RUN npm run setup && npm prune --production

RUN npm run build

##############
# PRODUCTION #
##############

FROM node:${NODE_VERSION} As production

WORKDIR /home/node

COPY --from=build /home/node/api/node_modules ./node_modules
COPY --from=build /home/node/api/dist ./dist

ENV PATH="$PATH:/home/node/api/node_modules/.bin"

RUN chown -R node:node /home/node/api
USER node

ENV NODE_ENV production

CMD [ "node", "dist/src/main.js" ]
```

```
version: '3.8'

services:
  db:
    # image: mongo # container image to be used
    # restart: always 
    # ports: # expose ports in “host:container” format
    #   - 27017:27017
    # environment: #env variables to pass into the container
    #    MONGODB_DATABASE: zombies
    image:  postgres
    restart: always 
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  dev:
    container_name: zombies_dev
    image: zombies-dev:1.0.0
    build:
      context: .
      target: install
      dockerfile: ./Dockerfile
    working_dir: /home/node/api
    command: npm run start:dev #:debug
    ports:
      - 3000:3000
      # - 9229:9229
    networks:
      - zombies-network
    volumes:
      - .:/home/node/api
      # - /home/node/api/node_modules
    restart: unless-stopped
  prod:
    container_name: zombies_prod
    image: zombies-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    working_dir: /home/node/api
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - zombies-network
    volumes:
      - .:/home/node
      - /home/node/api/node_modules
    restart: unless-stopped

networks:
  zombies-network:
```

project url https://github.com/testtestingtester/zombies-angular-nestjs

**Comment by ranisalt** [comment] 2022-12-10 18:27
@testtestingtester the project you sent does not seem to use this library. With that said, can you check the latest version (0.30.2)?

**Comment by testtestingtester** [comment] 2022-12-11 21:51
node:16 in the code I pasted but I tried with alpine different versions also, you want me to copy paste those configs? i think not...I'll try 0.30.2 but I'm thinking it's hopeless and probably won't work like the rest I tried...works on mac though

**Comment by testtestingtester** [comment] 2022-12-11 21:59
same error even with 0.30.2, i tried downgrading actually because I saw that was the fix others were saying...the project doesn't have the configs in the repo yet but if you try to add them and run `docker-compose up -d` you'll see it fails with the same error in docker, works on mac without docker just fine

**Comment by testtestingtester** [comment] 2022-12-12 20:07
using `bcryptjs` instead fixes my issue

**Comment by jsjoeio** [comment] 2022-12-19 21:30
Possibly getting the same error here:

```javascript
    /home/runner/work/code-server/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: invalid ELF header

      at Runtime._loadModule (test/node_modules/jest-runtime/build/index.js:1180:29)
      at Object.<anonymous> (node_modules/argon2/argon2.js:6:25)
```

Using `ubuntu-20.04` in CI with GitHub Actions and `0.30.2`

**Comment by sknight80** [comment] 2023-01-06 17:36
Hi,

Do you know if we have any updates here?  I have the same problem with the latest version of `argon2 @ 0.30.3` with `alpine.3.17`

**Comment by Slapbox** [comment] 2023-03-29 01:48
I just saw this for the first time I can ever recall using `0.30.3`, but we also just upgraded Electron so it could be that? But I wouldn't expect this error from upgrading Electron.

Regrettably my scrollback is too small and the error is already gone so I can't see if it was identical to @jsjoeio.

We're running Ubuntu 22.10.

**Comment by Slapbox** [comment] 2023-03-29 23:37
Just hit it again. We're downgrading to `0.29.x`.

If I don't report the issue anymore, it's probably safe to assume the issue is `0.30.x` and not the Electron upgrade - although I'll try to loop back more explicitly. @ranisalt

**Comment by ranisalt** [comment] 2023-03-30 12:27
@Slapbox I believe you have a different problem than the one in this issue. This one is caused by/within musl so unless it's happening in Alpine or Void it's not the same thing :P

**Comment by ranisalt** [comment] 2023-09-01 14:09
@Tallyrald it would be good if you can get the Alpine developers' attention on this issue, it's super hard to debug and when I traced the exception, it happens inside musl, so it's not something we can change from node-argon2

A bug report on their tracker should be enough to get the ball rolling.

**Comment by nekopsykose** [comment] 2023-09-04 22:24
this happens because the `argon2.node` plugin is precompiled. you cannot expect to run it on a non-glibc system (where it was originally compiled) and work. that it happened to sometimes work is just a fluke.

there is nothing alpine (or musl) can do to fix this. it works if you rebuild it:

```
> argon2-sigsegv-repro@1.0.0 start
> node ./built/index.js

[...]
npm ERR! signal SIGSEGV
[...]

$ npx @mapbox/node-pre-gyp rebuild -C node_modules/argon2
$ npm run start

> argon2-sigsegv-repro@1.0.0 start
> node ./built/index.js

$argon2id$v=19$m=65536,t=8,p=2$4ZxaYfo3wi4uQQcG5Iu+Jg$E/XmpSxdshGcocvDa/DHdcSpHiqvH7o4ckjY1GTUj2+qmPAxjJVIrsh/rWjEB2WAdn8
true
```

**Comment by nekopsykose** [comment] 2023-09-04 22:26
> there is nothing alpine (or musl) can do to fix this.  

the reason it sometimes happens to work is because musl has some degree of compatibility with glibc (ABI-wise), but it is neither complete nor guaranteed to work (so the older versions just so happened to only use the C api in such a way as to be compatible with either). and when it doesn't match up, having a different ABI than what you compiled against just crashes. there is nothing to do about that.

**Comment by ranisalt** [comment] 2023-09-04 23:28
> this happens because the `argon2.node` plugin is precompiled

The precompiled binary will be linked against musl if you are running Alpine.

The problem with the Dockerfile provided in this issue is that it installs dependencies under Debian, but then copies to Alpine and does not perform the install step again to refetch the precompiled binary.

**Comment by nekopsykose** [comment] 2023-09-04 23:31
> The precompiled binary will be linked against musl if you are running Alpine.  

in that case it would work fine, indeed this specific way of installing it would be broken :)

**Comment by nekopsykose** [comment] 2023-09-04 23:35
yeah, can confirm changing `FROM node:${NODE_VERSION}` to `FROM node:${NODE_VERSION}-alpine` alone works as expected

**Comment by Tallyrald** [comment] 2023-09-05 13:27
Thank you @nekopsykose and @ranisalt for your help. For my specific needs the final solution is to run a 2-step pre-build process before copying everything over to the final image.

- The first step builds most dependencies of the project that need the Debian-based Node image.
- The second step installs argon2 on an Alpine Node image.
- The final step is to copy over all dependencies into the target (Alpine-based) image that is used to run the finalized and prepared application.

For me, the problem is resolved now. If this is satisfactory for others too, please close this issue.
Thank you again for your help.

Just for reference, I asked for help in the Alpine issues board [HERE](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15241) which helped the issue move forward and be solved.

**Comment by ranisalt** [comment] 2023-09-05 13:50
@Tallyrald why do you _need_ to run it on Debian? Doesn't Alpine provide the tools you need to build this project?

**Comment by ranisalt** [comment] 2023-09-05 14:23
Alright, since the original problem has been solved, I'm closing the issue

**Closed by ranisalt** 2023-09-05 14:23 UTC
Labels: bug, help wanted
