### ISSUE TITLE
Package name fix for installation on m1 Macs

### ISSUE THREAD

**Issue by AvKat** [ranisalt/node-argon2#344] opened 2022-05-07 07:52 UTC
While installing argon2, I encountered an error with the following issue:
` node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.5/argon2-v0.28.5-napi-v3-darwin-arm64-unknown.tar.gz
`

Even though the files have been published, they follow a [different format](https://github.com/ranisalt/node-argon2/releases/tag/v0.28.2) for m1. 

I do not know why the build fails on my machine, but it would really help if there were prebuilt binaries.

**Comment by ranisalt** [comment] 2022-05-07 12:49
The files have not been published, we don't publish for M1s (yet - will do it soon)

This is a duplicate of #305, so follow the discussion there :)

**Closed by ranisalt** 2022-05-07 12:49 UTC
